# Use a recent Node LTS version
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy backend package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Add node_modules/.bin to PATH
ENV PATH /app/node_modules/.bin:$PATH

# Expose the port the backend will run on
EXPOSE 3000

# Default command to run the development server
CMD ["npm", "run", "dev"]
